# Site settings
title: Palbook27 Study Blog
description: 꿈꾸는 개발자
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://palbook27.github.io"
# User settings
username: palbook27의 스터디공간
user_description: 안녕하세요. 스터디를 하면서 남기는 공간입니다. Visit my blog here <a href="https://palbook27.github.io" target="_blank">https://palbook27.github.io</a>
user_title: Software Engineer
email: palbook27@gmail.com
# twitter_username: lorem_ipsum
# github_username:  palbook27
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
